info:
  contact: {}
  license: {}
paths:
  /api/v1/kubernetes/deploy:
    post:
      consumes:
      - application/json
      description: deploy services on kubernetes cluste
      produces:
      - application/json
      summary: deploy services on kubernetes cluster
  /api/v1/registry:
    delete:
      consumes:
      - application/json
      description: deploy services on kubernetes cluster
      produces:
      - application/json
      summary: deploy services on kubernetes cluster
    get:
      consumes:
      - application/json
      description: deploy services on kubernetes cluster
      produces:
      - application/json
      summary: deploy services on kubernetes cluster
    post:
      consumes:
      - application/json
      description: deploy services on kubernetes cluster
      produces:
      - application/json
      summary: deploy services on kubernetes cluster
  /api/v1/statefulsets/{name}/{namespace}:
    delete:
      consumes:
      - application/json
      description: get status of kubernetes services deployment on a Kubernetes Cluster.
        If you need all services status then pass namespace=""
      parameters:
      - description: Name of the kubernetes service
        in: path
        name: name
        required: true
        type: string
      - description: Namespace of the kubernetes service
        in: path
        name: namespace
        type: string
      produces:
      - application/json
      summary: get status of kubernetes services deployment
    get:
      consumes:
      - application/json
      description: get status of kubernetes services deployment on a Kubernetes Cluster.
        If you need all services status then pass namespace=""
      parameters:
      - description: Name of the kubernetes service
        in: path
        name: name
        required: true
        type: string
      - description: Namespace of the kubernetes service
        in: path
        name: namespace
        type: string
      produces:
      - application/json
      summary: get status of kubernetes services deployment
  /api/v1/statefulsets/{namespace}:
    get:
      consumes:
      - application/json
      description: get status of all kubernetes services deployment on a Kubernetes
        Cluster. If you need all services status then pass namespace=""
      parameters:
      - description: Namespace of kubernetes cluster
        in: path
        name: namespace
        type: string
      produces:
      - application/json
      summary: get status of  all kubernetes services deployment
