// Code generated by protoc-gen-go. DO NOT EDIT.
// source: k8s-resource.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KubernetesResourceRequest struct {
	InfrastructureId     string   `protobuf:"bytes,1,opt,name=infrastructure_id,json=infrastructureId,proto3" json:"infrastructure_id,omitempty"`
	CompanyId            string   `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Command              string   `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Namespaces           []string `protobuf:"bytes,5,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Args                 []string `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesResourceRequest) Reset()         { *m = KubernetesResourceRequest{} }
func (m *KubernetesResourceRequest) String() string { return proto.CompactTextString(m) }
func (*KubernetesResourceRequest) ProtoMessage()    {}
func (*KubernetesResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe78c8ff5de7b42, []int{0}
}

func (m *KubernetesResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesResourceRequest.Unmarshal(m, b)
}
func (m *KubernetesResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesResourceRequest.Marshal(b, m, deterministic)
}
func (m *KubernetesResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesResourceRequest.Merge(m, src)
}
func (m *KubernetesResourceRequest) XXX_Size() int {
	return xxx_messageInfo_KubernetesResourceRequest.Size(m)
}
func (m *KubernetesResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesResourceRequest proto.InternalMessageInfo

func (m *KubernetesResourceRequest) GetInfrastructureId() string {
	if m != nil {
		return m.InfrastructureId
	}
	return ""
}

func (m *KubernetesResourceRequest) GetCompanyId() string {
	if m != nil {
		return m.CompanyId
	}
	return ""
}

func (m *KubernetesResourceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *KubernetesResourceRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *KubernetesResourceRequest) GetNamespaces() []string {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *KubernetesResourceRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type KubernetesResourceResponse struct {
	Resource             []byte   `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesResourceResponse) Reset()         { *m = KubernetesResourceResponse{} }
func (m *KubernetesResourceResponse) String() string { return proto.CompactTextString(m) }
func (*KubernetesResourceResponse) ProtoMessage()    {}
func (*KubernetesResourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fe78c8ff5de7b42, []int{1}
}

func (m *KubernetesResourceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesResourceResponse.Unmarshal(m, b)
}
func (m *KubernetesResourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesResourceResponse.Marshal(b, m, deterministic)
}
func (m *KubernetesResourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesResourceResponse.Merge(m, src)
}
func (m *KubernetesResourceResponse) XXX_Size() int {
	return xxx_messageInfo_KubernetesResourceResponse.Size(m)
}
func (m *KubernetesResourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesResourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesResourceResponse proto.InternalMessageInfo

func (m *KubernetesResourceResponse) GetResource() []byte {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *KubernetesResourceResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*KubernetesResourceRequest)(nil), "proto.KubernetesResourceRequest")
	proto.RegisterType((*KubernetesResourceResponse)(nil), "proto.KubernetesResourceResponse")
}

func init() {
	proto.RegisterFile("k8s-resource.proto", fileDescriptor_6fe78c8ff5de7b42)
}

var fileDescriptor_6fe78c8ff5de7b42 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x8d, 0x6d, 0xaa, 0x1d, 0x45, 0x74, 0xf0, 0xb0, 0x06, 0x94, 0x98, 0x93, 0x20, 0xf6,
	0xa0, 0x17, 0xff, 0x81, 0x48, 0xc1, 0x43, 0x2e, 0x1e, 0x65, 0x9b, 0x4c, 0xa5, 0x94, 0xec, 0xc6,
	0x99, 0xdd, 0x83, 0xbf, 0xd1, 0x3f, 0x65, 0xba, 0x9b, 0x48, 0x05, 0xed, 0x29, 0x79, 0xef, 0x7d,
	0x2c, 0x6f, 0x1e, 0xe0, 0xfa, 0x51, 0xee, 0x98, 0xc4, 0x7a, 0xae, 0x68, 0xd6, 0xb2, 0x75, 0x16,
	0xd3, 0xf0, 0x29, 0xbe, 0x12, 0xb8, 0x98, 0xfb, 0x05, 0xb1, 0x21, 0x47, 0x52, 0xf6, 0x4c, 0x49,
	0x1f, 0x9e, 0xc4, 0xe1, 0x2d, 0x9c, 0xad, 0xcc, 0x92, 0xb5, 0x38, 0xf6, 0x95, 0xf3, 0x4c, 0x6f,
	0xab, 0x5a, 0x25, 0x79, 0x72, 0x33, 0x2d, 0x4f, 0x7f, 0x07, 0xcf, 0x35, 0x5e, 0x02, 0x54, 0xb6,
	0x69, 0xb5, 0xf9, 0xdc, 0x50, 0xfb, 0x81, 0x9a, 0xf6, 0x4e, 0x17, 0x9f, 0x43, 0xea, 0xec, 0x9a,
	0x8c, 0x1a, 0x85, 0x24, 0x0a, 0x54, 0x70, 0xd0, 0x21, 0x8d, 0x36, 0xb5, 0x1a, 0x07, 0x7f, 0x90,
	0x78, 0x05, 0x60, 0x74, 0x43, 0xd2, 0xea, 0x8a, 0x44, 0xa5, 0xf9, 0xa8, 0x0b, 0xb7, 0x1c, 0x44,
	0x18, 0x6b, 0x7e, 0x17, 0x35, 0x09, 0x49, 0xf8, 0x2f, 0x5e, 0x20, 0xfb, 0xeb, 0x18, 0x69, 0xad,
	0x11, 0xc2, 0x0c, 0x0e, 0x87, 0x11, 0xc2, 0x11, 0xc7, 0xe5, 0x8f, 0xde, 0xb4, 0x23, 0x66, 0xcb,
	0x7d, 0xef, 0x28, 0xee, 0x97, 0x70, 0xd4, 0x4d, 0x37, 0x3c, 0x84, 0xaf, 0x70, 0xf2, 0x44, 0x6e,
	0xbe, 0xe5, 0xe4, 0x71, 0xcd, 0xd9, 0xbf, 0x13, 0x66, 0xd7, 0x3b, 0x88, 0xd8, 0xab, 0xd8, 0x5b,
	0x4c, 0x02, 0xf3, 0xf0, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x92, 0xaa, 0x3a, 0xbc, 0xa9, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// K8SResourceClient is the client API for K8SResource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type K8SResourceClient interface {
	GetK8SResource(ctx context.Context, in *KubernetesResourceRequest, opts ...grpc.CallOption) (*KubernetesResourceResponse, error)
}

type k8SResourceClient struct {
	cc grpc.ClientConnInterface
}

func NewK8SResourceClient(cc grpc.ClientConnInterface) K8SResourceClient {
	return &k8SResourceClient{cc}
}

func (c *k8SResourceClient) GetK8SResource(ctx context.Context, in *KubernetesResourceRequest, opts ...grpc.CallOption) (*KubernetesResourceResponse, error) {
	out := new(KubernetesResourceResponse)
	err := c.cc.Invoke(ctx, "/proto.k8sResource/GetK8sResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// K8SResourceServer is the server API for K8SResource service.
type K8SResourceServer interface {
	GetK8SResource(context.Context, *KubernetesResourceRequest) (*KubernetesResourceResponse, error)
}

// UnimplementedK8SResourceServer can be embedded to have forward compatible implementations.
type UnimplementedK8SResourceServer struct {
}

func (*UnimplementedK8SResourceServer) GetK8SResource(ctx context.Context, req *KubernetesResourceRequest) (*KubernetesResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetK8SResource not implemented")
}

func RegisterK8SResourceServer(s *grpc.Server, srv K8SResourceServer) {
	s.RegisterService(&_K8SResource_serviceDesc, srv)
}

func _K8SResource_GetK8SResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KubernetesResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SResourceServer).GetK8SResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.k8sResource/GetK8SResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SResourceServer).GetK8SResource(ctx, req.(*KubernetesResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _K8SResource_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.k8sResource",
	HandlerType: (*K8SResourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetK8sResource",
			Handler:    _K8SResource_GetK8SResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "k8s-resource.proto",
}
