// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-01-21 18:12:43.8571135 +0500 PKT m=+0.047972601

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "info": {
        "contact": {},
        "license": {}
    },
    "paths": {
        "/api/v1/kubernetes/deploy": {
            "post": {
                "description": "deploy services on kubernetes cluste",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deploy services on kubernetes cluster"
            }
        },
        "/api/v1/registry": {
            "get": {
                "description": "deploy services on kubernetes cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deploy services on kubernetes cluster"
            },
            "post": {
                "description": "deploy services on kubernetes cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deploy services on kubernetes cluster"
            },
            "delete": {
                "description": "deploy services on kubernetes cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "deploy services on kubernetes cluster"
            }
        },
        "/api/v1/statefulsets/{namespace}": {
            "get": {
                "description": "get status of all kubernetes services deployment on a Kubernetes Cluster. If you need all services status then pass namespace=\"\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get status of  all kubernetes services deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace of kubernetes cluster",
                        "name": "namespace",
                        "in": "path"
                    }
                ]
            }
        },
        "/api/v1/statefulsets/{name}/{namespace}": {
            "get": {
                "description": "get status of kubernetes services deployment on a Kubernetes Cluster. If you need all services status then pass namespace=\"\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get status of kubernetes services deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the kubernetes service",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Namespace of the kubernetes service",
                        "name": "namespace",
                        "in": "path"
                    }
                ]
            },
            "delete": {
                "description": "get status of kubernetes services deployment on a Kubernetes Cluster. If you need all services status then pass namespace=\"\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get status of kubernetes services deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the kubernetes service",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Namespace of the kubernetes service",
                        "name": "namespace",
                        "in": "path"
                    }
                ]
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
